artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Sufyanhamza/End-to-End-ML-Project/raw/main/winequality-red.rar
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion